name: Streamlit Keep Alive

on:
  schedule:
    # This runs every 6 hours (Streamlit usually sleeps after 24-48h of inactivity)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: |
          curl -I -L https://autodocs-cbwzxc3rbdu89rxb7ik8pt.streamlit.app/